# Generated by Django 4.0.4 on 2022-05-05 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_placed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 18, 48, 5, 692069)),
        ),
    ]
