# Generated by Django 4.0.4 on 2022-05-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
