# Generated by Django 4.0.4 on 2022-05-05 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_alter_order_order_placed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_placed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
