# Generated by Django 4.0.4 on 2022-05-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_cartitem_product_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
